# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d829b456547dd2ea173ac4759072d0bc6e72b4c97ad91d2890fc3f575fc54442524dfeffd864557fe5869afeaa182ef4b85d1156ba964373cd62f49ac16f7df

test:
  secret_key_base: 2e1c7b9f67f400037acebe89c0124ace9e92a9e187ee596747fd7acfa54584442827c404b7b3cfe0581f2eafa34f012d9506fe845085fa72c93c898c574fb3bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
